# Generated by Django 4.1.6 on 2023-08-07 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transport.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_mc', models.CharField(max_length=7, unique=True, verbose_name='Company MC')),
                ('company_dot', models.CharField(max_length=7, verbose_name='Company DOT')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('company_address', models.CharField(max_length=255, verbose_name='Company address')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='Company Email')),
                ('company_phone', models.CharField(blank=True, max_length=20, verbose_name='Company phone')),
                ('company_prefix', models.CharField(blank=True, max_length=3, verbose_name='Company prefix')),
                ('company_default', models.CharField(blank=True, max_length=7, verbose_name='Default Company')),
                ('company_wire', models.TextField(blank=True, verbose_name='Wire instructions')),
                ('part_holding', models.BooleanField(default=False, verbose_name='Part holding')),
                ('company_logo', models.FileField(blank=True, upload_to=transport.models.get_file_path, verbose_name='Company logo')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTypeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Document name')),
            ],
        ),
        migrations.CreateModel(
            name='GenNumLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Status')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_broker_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Default_Broker_mc', to='transport.company', verbose_name='Default Broker for user')),
                ('load_carrier_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Default_Carrier_mc', to='transport.company', verbose_name='Default Carrier for user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Company_mc', to='transport.company', verbose_name='Company for user')),
            ],
        ),
        migrations.CreateModel(
            name='SellerLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Load number')),
                ('seller_load_number', models.CharField(db_index=True, max_length=30, verbose_name='Seller load number')),
                ('load_buy_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Seller price')),
                ('pickup_data', models.DateField(verbose_name='Pickup date')),
                ('pickup_time_from', models.TimeField(verbose_name='Time from')),
                ('pickup_time_to', models.TimeField(verbose_name='Time to')),
                ('pickup_location', models.TextField(verbose_name='Pickup Location')),
                ('pickup_instructions', models.TextField(verbose_name='Pickup Instructions')),
                ('destination_data', models.DateField(verbose_name='Destination date')),
                ('destination_time_from', models.TimeField(verbose_name='Time from')),
                ('destination_time_to', models.TimeField(verbose_name='Time to')),
                ('destination_location', models.TextField(verbose_name='Destination Location')),
                ('destination_instructions', models.TextField(verbose_name='Destination Instructions')),
                ('seller_MC', models.CharField(max_length=7, verbose_name='Seller MC')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date create load')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date update load')),
                ('company_mc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.company', verbose_name='Company MC')),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Load number')),
                ('load_buy_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Load buy price')),
                ('load_sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Load sell price')),
                ('load_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Load profit')),
                ('load_prefix_broker', models.CharField(max_length=3, verbose_name='Broker prefix')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date create load')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Load date update')),
                ('load_broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='load_broker', to='transport.company', verbose_name='Broker MC')),
                ('load_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='load_carrier', to='transport.company', verbose_name='Carrier MC')),
                ('stat', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='transport.status', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User name')),
            ],
            options={
                'verbose_name': 'Loads',
                'verbose_name_plural': 'Load',
                'ordering': ['-date_update'],
            },
        ),
        migrations.CreateModel(
            name='DocSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='ID seller load')),
                ('documents', models.FileField(upload_to=transport.models.get_file_path, verbose_name='Seller document')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.documentname', verbose_name='Seller documents name')),
            ],
        ),
        migrations.CreateModel(
            name='DocBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Load number')),
                ('documents', models.FileField(upload_to=transport.models.get_file_path, verbose_name='Buyer document')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.documentname', verbose_name='Buyer document name')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.companytypename', verbose_name='Company type'),
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_seller', models.CharField(blank=True, max_length=7, verbose_name='buyer / seller')),
                ('counterparty', models.CharField(blank=True, max_length=255, verbose_name='Counterparty')),
                ('cash_sum', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount')),
                ('transaction_data', models.DateField(verbose_name='Transaction date')),
                ('comment', models.TextField(blank=True, verbose_name='Purpose of payment')),
                ('executed', models.BooleanField(default=False, verbose_name='Executed')),
                ('payment_doc', models.FileField(upload_to=transport.models.get_file_path, verbose_name='Payment doc')),
                ('broker_carrier_mc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broker_carrier_mc', to='transport.company', verbose_name='Broker / Carrier MC')),
                ('buyer_seller_mc', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='buyer_seller_mc', to='transport.company', verbose_name='Buyer / Seller (holding)')),
                ('slug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.load', verbose_name='Load number')),
                ('transaction_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.transaction', verbose_name='Transaction type')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Load number')),
                ('truck_info', models.TextField(verbose_name='Truck info')),
                ('truck_requirements', models.TextField(verbose_name='Load info')),
                ('buyer_MC', models.CharField(max_length=7, verbose_name='Buyer MC')),
                ('date_sold_load', models.DateField(verbose_name='Sold date load')),
                ('load_sell_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Sell price')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date create load')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date update load')),
                ('company_mc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.company', verbose_name='Company MC')),
            ],
        ),
    ]
